LmycWebSite/Controllers/BoatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LmycDataLib.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace LmycWebSite.Controllers
{
    [Authorize]
    public class BoatsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Boats1
        public ActionResult Index()
        {
            return View(db.Boats.ToList());
        }

        // GET: Boats1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Boat boat = db.Boats.Find(id);
            if (boat == null)
            {
                return HttpNotFound();
            }
            return View(boat);
        }
        [Authorize(Roles = "Admin")]
        // GET: Boats1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Boats1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BoatId,BoatName,Picture,LengthInFeet,Make,Year,RecordCreationDate,CreatedBy")] Boat boat)
        {
            if (ModelState.IsValid)
            {
                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
                var user = userManager.FindByName(User.Identity.Name);
                boat.CreatedBy = user.Id;
                boat.RecordCreationDate = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff");
                db.Boats.Add(boat);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(boat);
        }

        [Authorize(Roles = "Admin")]
        // GET: Boats1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Boat boat = db.Boats.Find(id);
            if (boat == null)
            {
                return HttpNotFound();
            }
            return View(boat);
        }

        [Authorize(Roles ="Admin")]
        // POST: Boats1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BoatId,BoatName,Picture,LengthInFeet,Make,Year,RecordCreationDate,CreatedBy")] Boat boat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(boat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(boat);
        }

        // GET: Boats1/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Boat boat = db.Boats.Find(id);
            if (boat == null)
            {
                return HttpNotFound();
            }
            return View(boat);
        }

        [Authorize(Roles = "Admin")]
        // POST: Boats1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Boat boat = db.Boats.Find(id);
            db.Boats.Remove(boat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LmycWebSite/Controllers/UserMembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LmycDataLib.Models;
using LmycWebSite.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace LmycWebSite.Controllers
{
    public class UserMembersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: UserMembers
        public ActionResult Index()
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            //Get the list of Roles
            UserAndRolesHelper viewModel = new UserAndRolesHelper();
            viewModel.FirstTable = db.UserMembers.ToList();
            viewModel.SecondTable = db.AppRole.ToList();
            viewModel.ThirdTable = new List<KeyValuePair<string, string>>();

            //For each user, get their roles
            foreach(var user in viewModel.FirstTable)
            {
                //Returns a list of roles by their user id
                var rolesByUser = UserManager.GetRoles(user.Id);

                //Iterate through each role return per user and add to list
                for (int i = 0; i < rolesByUser.Count(); i++)
                {
                    var element = new KeyValuePair<String, String>(user.UserName, rolesByUser.ElementAt(i));
                    viewModel.ThirdTable.Add(element);
                }
            }

            if (TempData["RoleError"] != null) { 
                ViewBag.RoleError = TempData["RoleError"].ToString();
            } else if (TempData["RoleSuccess"] != null) {
                ViewBag.RoleSuccess = TempData["RoleSuccess"].ToString();
            } else if (TempData["UserError"] != null) {
                ViewBag.UserError = TempData["UserError"].ToString();
            } else if (TempData["UserSuccess"] != null) {
                ViewBag.UserSuccess = TempData["UserSuccess"].ToString();
            }
            return View(viewModel);
        }

        // GET: UserMembers/Edit/5
        public ActionResult Edit(string id)
        {
            ViewBag.roleName = new SelectList(db.AppRole, "roleName", "roleName");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserMembers userMembers = db.UserMembers.Find(id);
            if (userMembers == null)
            {
                return HttpNotFound();
            }
            return View(userMembers);
        }

        // POST: UserMembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,Firstname,LastName,Street,City,Province,PostalCode,Country,MobileNumber,SailingExperience,Role")] UserMembers userMembers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userMembers).State = EntityState.Modified;
                db.SaveChanges();

                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

                if (!UserManager.IsInRole(userMembers.Id, userMembers.Role))
                {
                    UserManager.AddToRole(userMembers.Id, userMembers.Role);
                    TempData["UserSuccess"] = "User successfully added to role";
                } else
                {
                    TempData["UserError"] = "User already in that role";
                }

                return RedirectToAction("Index");
            }
            return View(userMembers);
        }


        // GET: UserMembers/Delete/5
        public ActionResult Delete(string id)
        {
            ViewBag.roleName = new SelectList(db.AppRole, "roleName", "roleName");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (id == "" + 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            UserMembers userMembers = db.UserMembers.Find(id);
            if (userMembers == null)
            {
                return HttpNotFound();
            }
            return View(userMembers);
        }

        // POST: UserMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,Firstname,LastName,Street,City,Province,PostalCode,Country,MobileNumber,SailingExperience,Role")] UserMembers userMembers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userMembers).State = EntityState.Modified;
                db.SaveChanges();

                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

                if (UserManager.IsInRole(userMembers.Id, userMembers.Role))
                {
                    UserManager.RemoveFromRole(userMembers.Id, userMembers.Role);
                    TempData["UserSuccess"] = "User successfully removed from role";
                } else
                {
                    TempData["UserError"] = "User was not in that role";
                }

                return RedirectToAction("Index");
            }
            return View(userMembers);
            //UserMembers userMembers = db.UserMembers.Find(id);
            //db.Users.Remove(userMembers);
            //db.SaveChanges();
            //return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LmycWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LMYC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Styles/styles.css" rel="stylesheet" />
    <link href="~/Styles/landing.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-fixed-top" id="lmyc-navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LMYC", "Index", "Home", new { area = "" }, new { @class = "lmyc-navbar-logo" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (this.User.IsInRole("Admin") && User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Users & Roles", "Index", "UserMembers")</li>
                    }
                    @if ((this.User.IsInRole("Admin") || this.User.IsInRole("Member") || this.User.IsInRole("Members")) && User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Boat", "Index", "Boats")</li>
                    }

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - LMYC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LmycWebSite/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Boat", "Index", "Boats")</li>
                    <li>@Html.ActionLink("Users & Roles","Index","UserMembers")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LmycWebSite/Views/Shared/_LayoutPublic.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LmycWebSite/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LMYC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Styles/styles.css" rel="stylesheet" />
    <link href="~/Styles/landing.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LMYC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Boat", "Index", "Boats")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>