LmycWebSite/Controllers/AppRolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LmycDataLib.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace LmycWebSite.Controllers
{
    public class AppRolesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AppRoles
        public ActionResult Index()
        {
            return RedirectToRoute(new {controller = "UserMembers", action = "Index"});
        }

        // GET: AppRoles/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppRole appRole = db.AppRole.Find(id);
            if (appRole == null)
            {
                return HttpNotFound();
            }
            return View(appRole);
        }

        // GET: AppRoles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AppRoles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "roleName")] AppRole appRole)
        {
            if (ModelState.IsValid)
            {
                var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

                if (!roleManager.RoleExists(appRole.roleName))
                {
                    db.AppRole.Add(appRole);
                    db.SaveChanges();
                    var role = new IdentityRole();
                    role.Name = appRole.roleName;
                    roleManager.Create(role);
                    TempData["RoleSuccess"] = "Role successfully created";
                } else
                {
                    TempData["RoleError"] = "Role already created";
                }
                return RedirectToAction("Index");
            }

            return View(appRole);
        }

        // GET: AppRoles/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppRole appRole = db.AppRole.Find(id);
            if (appRole == null)
            {
                return HttpNotFound();
            }
            return View(appRole);
        }

        // POST: AppRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
                AppRole appRole = db.AppRole.Find(id);
                var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));
                if (appRole.roleName != "Admin" && roleManager.RoleExists(appRole.roleName))
                {
                    var role = roleManager.FindByName(appRole.roleName);
                    roleManager.Delete(role);
                    db.AppRole.Remove(appRole);
                    db.SaveChanges();
                    TempData["RoleSuccess"] = "Successfully removed role and all members in that role";
                }


                return RedirectToAction("Index");
            } catch (Exception E)
            {
                TempData["RoleError"] = "Cannot delete while there are members in that role";
                return RedirectToAction("Index");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LmycWebSite/Controllers/UserMembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LmycDataLib.Models;
using LmycWebSite.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace LmycWebSite.Controllers
{
    public class UserMembersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: UserMembers
        public ActionResult Index()
        {
            var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            //Get the list of Roles
            UserAndRolesHelper viewModel = new UserAndRolesHelper();
            viewModel.FirstTable = db.UserMembers.ToList();
            viewModel.SecondTable = db.AppRole.ToList();
            viewModel.ThirdTable = new List<KeyValuePair<string, string>>();

            //For each user, get their roles
            foreach(var user in viewModel.FirstTable)
            {
                //Returns a list of roles by their user id
                var rolesByUser = UserManager.GetRoles(user.Id);

                //Iterate through each role return per user and add to list
                for (int i = 0; i < rolesByUser.Count(); i++)
                {
                    var element = new KeyValuePair<String, String>(user.UserName, rolesByUser.ElementAt(i));
                    viewModel.ThirdTable.Add(element);
                }
            }

            if (TempData["RoleError"] != null) { 
                ViewBag.RoleError = TempData["RoleError"].ToString();
            } else if (TempData["RoleSuccess"] != null) {
                ViewBag.RoleSuccess = TempData["RoleSuccess"].ToString();
            } else if (TempData["UserError"] != null) {
                ViewBag.UserError = TempData["UserError"].ToString();
            } else if (TempData["UserSuccess"] != null) {
                ViewBag.UserSuccess = TempData["UserSuccess"].ToString();
            }
            return View(viewModel);
        }

        // GET: UserMembers/Edit/5
        public ActionResult Edit(string id)
        {
            ViewBag.roleName = new SelectList(db.AppRole, "roleName", "roleName");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserMembers userMembers = db.UserMembers.Find(id);
            if (userMembers == null)
            {
                return HttpNotFound();
            }
            return View(userMembers);
        }

        // POST: UserMembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,Firstname,LastName,Street,City,Province,PostalCode,Country,MobileNumber,SailingExperience,Role")] UserMembers userMembers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userMembers).State = EntityState.Modified;
                db.SaveChanges();

                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

                if (!UserManager.IsInRole(userMembers.Id, userMembers.Role))
                {
                    UserManager.AddToRole(userMembers.Id, userMembers.Role);
                    TempData["UserSuccess"] = "User successfully added to role";
                } else
                {
                    TempData["UserError"] = "User already in that role";
                }

                return RedirectToAction("Index");
            }
            return View(userMembers);
        }


        // GET: UserMembers/Delete/5
        public ActionResult Delete(string id)
        {
            ViewBag.roleName = new SelectList(db.AppRole, "roleName", "roleName");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (id == "" + 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            UserMembers userMembers = db.UserMembers.Find(id);
            if (userMembers == null)
            {
                return HttpNotFound();
            }
            return View(userMembers);
        }

        // POST: UserMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed([Bind(Include = "Id,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,Firstname,LastName,Street,City,Province,PostalCode,Country,MobileNumber,SailingExperience,Role")] UserMembers userMembers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userMembers).State = EntityState.Modified;
                db.SaveChanges();

                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

                if (UserManager.IsInRole(userMembers.Id, userMembers.Role))
                {
                    UserManager.RemoveFromRole(userMembers.Id, userMembers.Role);
                    TempData["UserSuccess"] = "User successfully removed from role";
                } else
                {
                    TempData["UserError"] = "User was not in that role";
                }

                return RedirectToAction("Index");
            }
            return View(userMembers);
            //UserMembers userMembers = db.UserMembers.Find(id);
            //db.Users.Remove(userMembers);
            //db.SaveChanges();
            //return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LmycWebSite/Views/UserMembers/Create.cshtml
@model LmycDataLib.Models.UserMembers

@{
    ViewBag.Title = "Create";
}

<div class="content-body">
    <h2>Create</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>UserMembers</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.EmailConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.EmailConfirmed)
                        @Html.ValidationMessageFor(model => model.EmailConfirmed, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PasswordHash, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PasswordHash, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SecurityStamp, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SecurityStamp, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SecurityStamp, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumberConfirmed, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.PhoneNumberConfirmed)
                        @Html.ValidationMessageFor(model => model.PhoneNumberConfirmed, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TwoFactorEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.TwoFactorEnabled)
                        @Html.ValidationMessageFor(model => model.TwoFactorEnabled, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LockoutEndDateUtc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LockoutEndDateUtc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LockoutEndDateUtc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LockoutEnabled, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.LockoutEnabled)
                        @Html.ValidationMessageFor(model => model.LockoutEnabled, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.AccessFailedCount, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AccessFailedCount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AccessFailedCount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Street, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Street, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Province, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Province, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Province, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SailingExperience, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SailingExperience, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SailingExperience, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    </div>

LmycWebSite/Views/UserMembers/Delete.cshtml
@model LmycDataLib.Models.UserMembers
@{
    ViewBag.Title = "Remove";
}

<div class="content-body">
    <h2>Remove Role</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.EmailConfirmed)
            @Html.HiddenFor(model => model.PasswordHash, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.SecurityStamp, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.PhoneNumberConfirmed)
            @Html.HiddenFor(model => model.TwoFactorEnabled)
            @Html.HiddenFor(model => model.LockoutEndDateUtc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.LockoutEnabled)
            @Html.HiddenFor(model => model.AccessFailedCount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.Street, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.Province, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.HiddenFor(model => model.SailingExperience, new { htmlAttributes = new { @class = "form-control" } })
            <div class="form-group">
                @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Role", (SelectList)ViewBag.roleName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Remove" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

LmycWebSite/Views/UserMembers/Details.cshtml
@model LmycDataLib.Models.UserMembers

@{
    ViewBag.Title = "Details";
}

<div class="content-body">
    <h2>Details</h2>

    <div>
        <h4>UserMembers</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EmailConfirmed)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EmailConfirmed)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PasswordHash)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PasswordHash)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SecurityStamp)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SecurityStamp)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PhoneNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PhoneNumberConfirmed)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.TwoFactorEnabled)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TwoFactorEnabled)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LockoutEndDateUtc)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LockoutEnabled)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LockoutEnabled)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AccessFailedCount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AccessFailedCount)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Firstname)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Firstname)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Street)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Street)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Province)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Province)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.PostalCode)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.PostalCode)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Country)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Country)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MobileNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MobileNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SailingExperience)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SailingExperience)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Role)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Role)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
    </div>

LmycWebSite/Views/UserMembers/Index.cshtml
@model LmycWebSite.Models.UserAndRolesHelper

@{
    ViewBag.Title = "Index";
}

<div class="content-body">
    <h2>Index</h2>
<div class="text-success">
    @ViewBag.UserSuccess
</div>
<div class="text-danger">
    @ViewBag.UserError
</div>
<table class="table">
    <tr>
        <th>
            Email
        </th>
        <th>
            User Name
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.FirstTable)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.ActionLink("Add Role", "Edit", new { id = item.Id })
                |
                @Html.ActionLink("Remove Roles", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

<p>
    @Html.ActionLink("Create New Role", "Create", "AppRoles", null, null)
</p>
<div class="text-success">
    @ViewBag.RoleSuccess
</div>
<div class="text-danger">
    @ViewBag.RoleError
</div>
<h2>Roles</h2>
<table>
    <tr>
        <th>
            Role Name
        </th>
    </tr>
    @foreach (var item in Model.SecondTable)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.roleName)
            </td>
            <td>
              @if (item.roleName != "Admin")
                {
                 @Html.ActionLink("Delete", "Delete", "AppRoles", new { id = item.roleName }, null)
                }
            </td>
        </tr>
    }
</table>

<br />
<h2>Users and Their roles</h2>
<table>
    <tr>
        <th>
            User
        </th>
        <th>
            Role
        </th>
    </tr>
    @foreach (var item in Model.ThirdTable)
    {
        <tr>
            <td>
                @item.Key
            </td>
            <td>
                @item.Value
            </td>
        </tr>
    }
</table>
</div>